modLoader = "javafml"
loaderVersion = "[43,)"
license = "All Rights Reserved"

[[mods]]
modId = "betterwitches"
version = "${file.jarVersion}"
displayName = "BetterWitches"
authors = "MrStupsi"
description = '''
A Mod which adds new stuff for witches
'''

[[dependencies.betterwitches]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.betterwitches]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"